# Generated by Django 4.1.5 on 2023-03-29 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_izlenenler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izlenenler',
            name='izlenen',
            field=models.ManyToManyField(null=True, to='movies.movies'),
        ),
        migrations.AlterField(
            model_name='izlenenler',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
